#porta do eureka server
server:
   port: ${PORT}

#Srpring security
ead:
   serviceRegistry:
      username: ${EUREKA_USERNAME}
      password: ${EUREKA_PASSWORD}

#PARA A APLICAÇÃO STARTAR APENAS COMO SERVIDOR
eureka:
   client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
         defaultZone: ${EUREKA_URL}
   instance:
      hostname: ${APP_DOMAIN_NAME}
      non-secure-port: 80
   #colorir mensagens no terminal windows
   output:
      ansi:
         enabled: ALWAYS
