#porta do gateway
server:
  port: 8080

spring:
  application:
    name: ead-api-gateway
  cloud:
    gateway:
      routes:
        - id: authuser-service
          uri: lb://EAD-AUTHUSER-SERVICE
          predicates:
            - Path=/ead-authuser/**
        - id: course-service
          uri: lb://EAD-COURSE-SERVICE
          predicates:
            - Path=/ead-course/**
        -  id: notification-service
           uri: lb://EAD-NOTIFICATION-SERVICE
           predicates:
             - Path=/ead-notification/**
        - id: payment-service
          uri: lb://EAD-PAYMENT-SERVICE
          predicates:
            - Path=/ead-payment/**
  #colorir mensagens no terminal windows
  output:
    ansi:
      enabled: ALWAYS


#Srpring security
ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead1224service'

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost