server:
  port: 8087

spring:
  application:
    name: authuser
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: 1224
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation:true
    properties:
      hibernate:
        show_sql: true



