server:
  port: 8087

spring:
  application:
    name: authuser
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: 1224
  jpa:
    hibernate:
      ddl-auto:update
      dialect:org.hibernate.dialect.PostgreSQLDialect
      jdbc:lob:non_contextual_creation=true
    show_sql: true
    properties:
      hibernate: format_sql=true
    open-in-view: false
#colorir mensagens no terminal windows
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO


