spring:
  application:
    name: ead-authuser-service
  profiles:
     active: prod
  openfeign:
        client:
          config:
            feignName:
              connectTimeout: 5000
              readTimeout: 5000
              loggerLevel: basic

