spring:
   config:
      import: 'configserver:'
   cloud:
      config:
         discovery:
            service-id: ead-config-server
         username: configServerprod
         password: 'ead1224serverprod'
