server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost

spring:
  application:
    name: ead-authuser-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: 1224
  jpa:
    hibernate:
      ddl-auto:update
      dialect:org.hibernate.dialect.PostgreSQLDialect
      jdbc:lob:non_contextual_creation=true
    properties:
      hibernate:
         format_sql=true
    open-in-view: false
    show-sql: true
    generate-ddl: true



#colorir mensagens no terminal windows
  output:
    ansi:
      enabled: ALWAYS

ead:
  api:
    url:
      course: 'http://ead-course-service'

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    web: DEBUG
    org.hibernate: INFO

