server:
  port: 8082

spring:
  application:
    name: course
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: 1224
  jpa:
    show-sql: true
    properties:
      hibernate: show_sql:true
      jdbc:
        lob:non_contextual_creation=true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect