server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost



spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: 1224
  jpa:
    hibernate:
      ddl-auto:update
      dialect:org.hibernate.dialect.PostgreSQLDialect
      jdbc:lob:non_contextual_creation=true
    show_sql: true
    properties:
      hibernate: format_sql=true
    open-in-view: false
    generate-ddl: true

    #colorir mensagens no terminal windows
  output:
   ansi:
    enabled: ALWAYS

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service'

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    web: DEBUG
    org.hibernate: INFO




