server:
  port: 8082

spring:
  application:
    name: course
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: 1224
  jpa:
    hibernate:
      ddl-auto:update
      dialect:org.hibernate.dialect.PostgreSQLDialect
      jdbc:lob:non_contextual_creation=true
    show_sql: true
    properties:
      hibernate: format_sql=true
    open-in-view: false

