server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      #label: asyncronous
      server:
        git:
          uri: https://github.com/juniorbrandaol/decoder
          default-label: asyncronous
          username:
          password:
  output:
    ansi:
      enabled: ALWAYS

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname : localhost



